# yaml-language-server: $schema=./settings.schema.yaml

arrivalLabelLayouts:
  VHHHTMC:
    - {src: assignedRunway, w: 4}
    - {src: callSign, w: 9}
    - {src: assignedStar, w: 4, maxLen: 3}
    - {src: timeToLoseOrGain, w: 4, align: left}
    - {src: estimatedArrivalTime, timeFormat: mm, w: 3, align: right}

  VHHHAPP:
    - {src: assignedRunway, w: 4}
    - {src: callSign, w: 9}
    - {src: assignedStar, w: 4, maxLen: 3}
    - {src: timeToLoseOrGain, w: 4, align: left}
    - {src: scheduledLandingTime, timeFormat: mm, w: 3, align: right}
  
departureLabelLayouts:
  VHHHDEP:
    - {src: assignedRunway, w: 4}
    - {src: callSign, w: 8}
    - {src: aircraftType, w: 5}

connectionConfig:
  atcClient:
    host: "localhost"
    port: 12345
  masterSlaveApi:
    host: "https://aman-dman-api.fly.dev"

theme: "JTattoo"

planningSettings:
  useGroundspeedOnDirectRouting: true
